services:
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    depends_on:
      - postgres
      - redis
    build: backend
  nginx:
    depends_on:
      - backend
      - frontend
    build: nginx
    restart: always
    ports:
     - "3050:80"
  postgres:
    image: "postgres:alpine3.16"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "abcd1234"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass abcd1234
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master