apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: development
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv